apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
        - name: spring
          image: ika71/graduation-spring:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: MYSQL_URL
              value: graduation-mysql.mysql.database.azure.com
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: spring
            - name: MYSQL_USER
              value: ika71
            - name: MYSQL_PASSWORD
              value: <PASSWORD>
            - name: ACCESS_SECRET_KEY
              value: <SECRET KEY>
            - name: REFRESH_SECRET_KEY
              value: <SECRET KEY>
            - name: ADMIN_EMAIL
              value: admin@admin.com
            - name: ADMIN_NAME
              value: admin
            - name: ADMIN_PASSWORD
              value: <PASSWORD>
          volumeMounts:
            - name: spring-image
              mountPath: /app/images
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: spring-image
          persistentVolumeClaim:
            claimName: ika71-azurefile
